### ISSUE TITLE
小白问一下这个该怎么用？

### ISSUE THREAD

**Issue by yklawei** [hyzaw/scripts#2]
如有冒犯请勿怪，谢谢

**Comment by hyzaw** [comment]
很难跟你解释啊

**Comment by lingyle** [comment]
> 很难跟你解释啊

解释不来的，懂的自然懂
另外一个问题，pk脚本报错
获取Pk列表
TypeError: Cannot read property 'data' of null
    at /scripts/raw_ddo_pk.js:192:23
    at /scripts/raw_ddo_pk.js:713:15
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

先谢过大神

**Comment by hyzaw** [comment]
很难跟你解释啊

> > 很难跟你解释啊
> 
> 解释不来的，懂的自然懂
> 另外一个问题，pk脚本报错
> 获取Pk列表
> TypeError: Cannot read property 'data' of null
> at /scripts/raw_ddo_pk.js:192:23
> at /scripts/raw_ddo_pk.js:713:15
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> 
> 先谢过大神

重新拉一下脚本 改api地址了

**Comment by yklawei** [comment]
> 很难跟你解释啊

首先谢谢回复。那么有没有相关的教程或者关键词我去搜索学习学习。

**Comment by hyzaw** [comment]
> > 很难跟你解释啊
> 
> 首先谢谢回复。那么有没有相关的教程或者关键词我去搜索学习学习。

https://github.com/whyour/qinglong

**Comment by yklawei** [comment]
> > > 很难跟你解释啊
> > 
> > 
> > 首先谢谢回复。那么有没有相关的教程或者关键词我去搜索学习学习。
> 
> https://github.com/whyour/qinglong

多谢。完全看不明白。哈哈
